name: Java CI with Maven

on: # wann lößt die action aus?
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: # was soll passieren?
  build:

    runs-on: ubuntu-latest # Operating System

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
